WIDTH = 720
HEIGHT = 720

SCREEN_WIDTH = 875
SCREEN_HEIGHT = 721
DIMENSION = 9
CELL_SIZE = 47.5 # = 64
GRID = (80,105,57.5)

MAX_FPS = 15
BUT_WIDTH = BUT_HEIGHT = 62.5
BACKWARD_X = WIDTH
BACKWARD_Y = HEIGHT/2 - BUT_HEIGHT/2

NEXTSTEP_X = SCREEN_WIDTH - BUT_WIDTH
NEXTSTEP_Y = HEIGHT/2 - BUT_HEIGHT/2

REVERSE_X =SCREEN_WIDTH - BUT_WIDTH - BUT_WIDTH + 15
REVERSE_Y = HEIGHT/2 - BUT_HEIGHT/2 - BUT_WIDTH

START_X = WIDTH/2 - BUT_WIDTH/2 
START_Y = HEIGHT/2 - BUT_HEIGHT/2


REPLAY_X = SCREEN_WIDTH - BUT_WIDTH- BUT_WIDTH +15
REPLAY_Y = HEIGHT/2 - BUT_HEIGHT/2 + BUT_WIDTH

BUT_TEXT = 300
BUTTEXT_X = SCREEN_WIDTH/2 - BUT_TEXT/2
BUTTEXT_Y = HEIGHT/2 - BUT_TEXT/2

TITLE_WIDTH = 300
TITLE_WIDTH_X = SCREEN_WIDTH/2 
TITLE_HEIGHT_Y = 100